### ISSUE TITLE
make it work with Java 1.6

### ISSUE THREAD

**Issue by cpanse** [protViz/deisotoper#78]
- remove lambda functions for Java 7
```
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/dto/MassSpecMeasureSummary.java:[42,80] lambda expressions are not supported in -source 1.7
  (use -source 8 or higher to enable lambda expressions)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INF
```

- diamond operator for Java 6

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mgf/WriteMGF.java:[32,13] try-with-resources is not supported in -source 1.6
  (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/dto/MassSpecMeasureSerializer.java:[23,13] try-with-resources is not supported in -source 1.6
  (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mspy/Peaklist.java:[26,42] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/dto/MassSpecMeasureSummary.java:[23,51] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/dto/MassSpecMeasureSummary.java:[42,80] lambda expressions are not supported in -source 1.6
  (use -source 8 or higher to enable lambda expressions)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mgf/ReadMGF.java:[34,13] try-with-resources is not supported in -source 1.6
  (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mgf/ReadMGF.java:[63,45] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Configuration.java:[15,59] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/dto/MassSpectrum.java:[15,45] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicCluster.java:[12,56] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicClusterGraph.java:[27,81] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/R/FeaturesBasedDeisotoping.java:[29,53] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mspy/Mspy.java:[22,47] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mspy/Convert.java:[18,41] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mspy/Convert.java:[23,13] try-with-resources is not supported in -source 1.6
  (use -source 7 or higher to enable try-with-resources)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/Deisotoper.java:[22,60] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mgf/ReadStdIn.java:[33,45] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/PeakList.java:[17,49] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/dto/MassSpecMeasure.java:[12,65] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/fbdm/IsotopicSet.java:[46,60] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[ERROR] /home/cp/__checkouts/R/deisotoper/java/deisotoper/src/main/java/ch/fgcz/proteomics/mspy/Deisotoper.java:[25,54] diamond operator is not supported in -source 1.6
  (use -source 7 or higher to enable diamond operator)
[INFO] 21 errors 
```

**Comment by LukeCaruzo** [comment]
How did you test the compatibility for Java 1.6? @cpanse

**Comment by cpanse** [comment]
<img width="1216" alt="screen shot 2017-12-04 at 06 23 00" src="https://user-images.githubusercontent.com/4901987/33549031-8351d568-d8e9-11e7-8589-08849125d7f7.png">

can be set in the pom.xml file also (for testing) you have to define a new target
